# Generated by Django 4.1.13 on 2024-11-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=20)),
                ('part_no', models.CharField(max_length=15)),
                ('part_description', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('lot_no', models.CharField(max_length=10)),
                ('vehicle', models.CharField(max_length=17)),
                ('category', models.CharField(max_length=5)),
                ('reason_code', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='default', max_length=15)),
                ('lot', models.CharField(max_length=10)),
                ('vin_no', models.CharField(max_length=17)),
                ('engine_no', models.CharField(default='default', max_length=15)),
                ('gearbox_no', models.CharField(blank='False', default='default', max_length=15)),
                ('cabin_no', models.CharField(blank=True, max_length=15, null=True)),
                ('front_axle_no', models.CharField(max_length=15)),
                ('rear_axle1_no', models.CharField(max_length=15)),
                ('rear_axle2_no', models.CharField(blank=True, max_length=15, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=15)),
                ('model_code', models.CharField(max_length=15)),
                ('customer', models.CharField(max_length=15)),
            ],
        ),
    ]
