# Generated by Django 4.1.13 on 2024-11-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_customer_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleDetails',
            new_name='Vehicle',
        ),
    ]
