# Generated by Django 4.1.13 on 2024-11-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_rename_vehicledetails_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gearbox_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=15),
        ),
    ]
