# Generated by Django 4.1.13 on 2024-11-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_vehicle_engine_no_alter_vehicle_gearbox_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenealogyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel')),
            ],
        ),
        migrations.RenameModel(
            old_name='VehicleModels',
            new_name='VehicleModel',
        ),
    ]
