# Generated by Django 4.1.13 on 2024-12-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_genealogyfile_rename_vehiclemodels_vehiclemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brakeTest', models.BooleanField(default=False)),
                ('wheelAlignment', models.BooleanField(default=False)),
                ('diagnosis', models.BooleanField(default=False)),
                ('roadTest', models.BooleanField(default=False)),
                ('qc', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.vehicle')),
            ],
        ),
    ]
