# Generated by Django 4.1.13 on 2024-12-01 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_eol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('manning', models.IntegerField(blank=True)),
                ('duration', models.IntegerField(blank=True)),
                ('date', models.DateTimeField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.vehicle')),
            ],
        ),
    ]
