# Generated by Django 4.1.13 on 2024-12-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_rework'),
    ]

    operations = [
        migrations.AddField(
            model_name='eol',
            name='remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='eol',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production.vehicle'),
        ),
        migrations.AlterField(
            model_name='rework',
            name='details',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
