# Generated by Django 4.1.13 on 2024-10-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavMainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100, unique=True, verbose_name='Menu Name')),
                ('menu_id', models.CharField(default='', max_length=100, verbose_name='Menu ID')),
                ('icon', models.CharField(default='', max_length=100, verbose_name='Icon Name')),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Main_menu',
            },
        ),
        migrations.CreateModel(
            name='NavSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_menu_name', models.CharField(max_length=100, verbose_name='Submenu Name')),
                ('application_name', models.CharField(default='', max_length=50, verbose_name='App Name')),
                ('url', models.CharField(default='#', max_length=100, verbose_name='Url')),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('navmainmenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbmaster.navmainmenu')),
            ],
            options={
                'verbose_name_plural': 'Sub_menu',
            },
        ),
    ]
